### PR TITLE
feat: added support for typescript

### PR DESCRIPTION
**Pull request by shailesh-daund**

### CODE REVIEW

**Comment by shailesh-daund** [comment]
@MalcomnM Please look into this PR.

**Comment by shailesh-daund** [comment]
@MalcomnM Can you please look into this PR & release new version.

**Comment by MalcomnM** [comment]
I apologize for the slow response. I just reviewed and approved.

**Comment by MalcomnM** [comment]
@shailesh-daund , I have also published an updated version to npm, 1.0.1.

I will make sure to keep an eye out for future PRs.

**Comment by shailesh-daund** [comment]
@MalcomnM Can you please publish another version with NPM, as 1.0.1 is not updated with this changes

**Comment by MalcomnM** [comment]
@shailesh-daund , Version 1.0.3 has the typescript definitions now.

**Pull request merged**
